### ISSUE TITLE
Consider adding support for an installation process that provides a `VERSION` file

### ISSUE THREAD

**Issue by portante** [perftool-incubator/bench-trafficgen#29]
It would be great for the `pbench-trafficgen` functionality to not have to "know" how to install `bench-trafficgen`.  We have a `Draft` PR, https://github.com/distributed-system-analysis/pbench/pull/2375, which illustrates how we could take advantage of that.

This gives the `bench-trafficgen` the freedom to do whatever it wants with how to provide the code, where no knowledge of `git` or build processes need to be kept with `pbench-trafficgen` or any other consumer.  The "interface" is the agreed upon installation directory (currently `/opt/bench-trafficgen`), a `VERSION` file, and the known locations of the built executables within the installation directory.

**Comment by k-rister** [comment]
Our current system works fine for our needs and we have no need to change it.
