### ISSUE TITLE
Enhance rx packet counting by using pure vendor agnostic software paths

### ISSUE THREAD

**Issue by mrbojangles3** [perftool-incubator/bench-trafficgen#75]
Currently rx packet counting leverages vendor specific code. The desired architecture uses vendor agnostic code to count rx packets. A potential solution to this is to use multiple RX threads to monitor / count a subset of RX queues. The goal is to  have a count of packets *per* stream aka *pg_id* in TRex terms, without NIC vendor specific code.

- [ ] Move to a current version of Trex
- [ ] Gain understanding of how Trex uses dpdk currently
- [ ] Document the conditions that will cause a single RX thread to miss information (aka where it breaks)
- [ ] Implement the correct queue/thread/core/RSS cocktail in crucible
- [ ] Verify that multi-RX threads do not drop / throttle/ miss info (that it doesn't break)

**Comment by mrbojangles3** [comment]
After Bill showed me how the crucible automation around trex works, I am learning how to run trex by hand so I can learn about the tool underneath the automation. 

The goal of this work is to improve our usage of trex so that we are no longer tied to a specific vendors implementation of an offload for accurate flow counting inside of a traffic generation scenario. Once we are no longer tied, we will be able to use this automation in more places and at a greater scale.

**Comment by mrbojangles3** [comment]
The system is setup in loop back mode to eliminate other variables while looking for the maximum performance of software mode for trex. Work has been slowed by childcare issues.

The goal of this work is to improve our usage of trex so that we are no longer tied to a specific vendors implementation of an offload for accurate flow counting inside of a traffic generation scenario. Once we are no longer tied, we will be able to use this automation in more places and at a greater scale.

**Comment by mrbojangles3** [comment]
Learning stateless mode of trex, the scapy interface, etc. Looking into the special flags that trex has for the intel X710. The ultimate goal being to do what we do today in trex software mode. The current top of mind debugging issue is why is rx_cpu_util zero when using --software --no-hw-flow-stat flags and non-zero without it. We use that metric to make sure we aren't overwhelming the rx cpu and then losing data

**Comment by k-rister** [comment]
@mrbojangles3 @atheurer 

From the docs (https://trex-tgn.cisco.com/trex/doc/trex_manual.html#_command_line_options):

```
--software

Since version 2.21.

Do not configure any hardware rules. In this mode, all RX packets will be processed by software. No HW assist for dropping (while counting) packets will be used. This mode is good for enabling features like per stream statistics, and latency, support packet types, not supported by HW flow director rules (For example QinQ).

You can also use this mode for running TRex on interfaces which manifest themselves as ones supported by TRex, but in reality support less hardware capabilities. For example, NICs supported by DPDK e1000_igb driver, but with different HW capabilities than i350.

Drawback of this is that because software has to handle all received packets, total rate of RX streams is significantly lower. Up until v2.49 (not include) this mode is also limited to using only one TX core (and one RX core as usual). Now it uses multi-queue for RX and TX mainly for scale of virtual interfaces.
```

The last paragraph is the most important one.  In versions newer than v2.49 using `--software` automatically gets you into multi-queue RX and TX where the RX and TX load is consolidated on the same collection of CPUs that were previously just used for TX, essentially the RX thread goes away and all load shifts to the TX thread(s).  This may be exactly what we want but it will probably require tuning to determine the proper CPU configuration -- note that historically we have seen TRex not perform adequately when the utilization of the multi-queue TX CPUs exceeds 80% (I believe you were seeing 99%).

**Comment by mrbojangles3** [comment]
Based on above feedback and via slack I am running and collecting more data. I have started running with the latest version of trex to pickup any bug fixes with software mode. This is still a major learning process. Spent some time this week updating a crucible parser as well.

**Comment by mrbojangles3** [comment]
Based on a conversation in the weekly status meeting, we are switching to a system with more CPU cores since the CPU is becoming the limiting factor in my haswell era machine.

**Comment by mrbojangles3** [comment]
New nics and switch configuration are in place. Switching to the cascade lake system allows for more cores to be utilized. We are still seeing a lot of queue_full messages with this setup. I am going to explore allowing more cores to be used for trex.

**Comment by mrbojangles3** [comment]
By using a combination of flags, a stream count that matches 1:1 to the cores used, small packets,  we are getting closer to the goal of sending line rate packets per second without maxing out the cpus. The next step is to investigate the inter-stream-gap (trex config option) and the configured packets per second. Another way to state the goal is figuring out how many cpu cores are needed per port to max out the line rate of packets per second, once we have that info it will be trying to achieve the most packets per second that a box can do.

**Comment by mrbojangles3** [comment]
Using the standard trex, tui gives insufficient data. I am going to switch to just using a standalone part of crucibles trafficgen project. I am looking to use software mode on the nics, and ensure that the packets tx == packets rx and that the system will operate at the requested speed. for example if you ask trex to send 40% of line rate it is important that it is actually capable of doing that.

**Comment by dustinblack** [comment]
test comment for jira automation

**Comment by mrbojangles3** [comment]
Moved to a cropped version of crucible on a second vendors nic. This nic hasn't been used a much in our testing but offers the link speed we want. I am currently using the binary search setup from bench-trafficgen to diagnose / discover limitations with this NIC. Short weeks due to PTO.

**Comment by mrbojangles3** [comment]
Currently the desired configuration of trex on higher bandwidth NICs isn't yielding the desired performance. We are going to start debugging the trex application itself to gain more understanding of how the rx work is split amongst the cores and queues.

**Comment by mrbojangles3** [comment]
Using trex and perf we discover that rx processing isn't being given enough time. Even when sending unidirectional traffic from port 0 -> 1 the rx processing is minimal.  We are looking to find out what policy governs the split between tx and rx threads. Potential next steps include asking the mailing list, source code review, and or using dummy ports to help separate ports and cores.

**Comment by mrbojangles3** [comment]
Started a conversation on the mailing list related to how cores balance their time between TX and RX in `--software` mode. Continue to do our own testing to try to achieve zero loss at line rate. With the slower adaptors XV710 we are able to get a zero loss line rate test but we have to use a single port on two different cards to generate  / receive unidirectional traffic flow. The problem is we want to do this on a single 100Gbps card.

**Comment by mrbojangles3** [comment]
This week, I have been diving into the code in an effort to get RX work to be explicitly scheduled on cores that are not set to TX. This is after the experiment where two cards were used to separate work in a set of CPUS. We were able to have port 0 on card 1 dedicate all cores to tx and port 1 on card 1 dedicate all cores to RX. We had to have a second real card act as the port pairs for the transmitting and receiving cards. This was able to happen on two slower cards. Since the system doesn't have two 100Gbps nics we aren't able to try this trick. We also can't mix'n'match cards with different drivers.

**Comment by mrbojangles3** [comment]
Exploration continues. I am adding logging messages to Trex. I have also asked the mailing list for help identifying the areas of the code base that can offer help in adding the RX pinning. Trex lack an architecture document so new commiters are left to sift through the code, which takes time.

**Comment by mrbojangles3** [comment]
work resuming after PTO. Mailing list guidance changed directions. I am  now adding code from the "ground up" to dedicate CPU time to RX work. I have to make a change all the way through a few call trees. I have started this effort and plan to be on this path for a few weeks at least.

**Comment by sferlin** [comment]
Are you able to keep a clear map of CPU and NIC ports to the RX and TX paths of trex isolated?
One major thing I miss in trex is any sort of latency measurements (OWD or RTT).
I see you are in touch other team members, I was about the leave this posted [here](https://github.com/perftool-incubator/bench-trafficgen).

**Comment by mrbojangles3** [comment]
A late update. I am continuing to dive into the source code. Using the existing code path to initialize an RX cpu gave me a runtime error, "double watchdog". I disabled the watchdog via cli flags and started again, now the code is failing an assertion, which is next on my list to address.

**Comment by sferlin** [comment]
You probably did your portion of high-speed software-based traffic generator tools. I have just received a recommendation for [fastClick](https://orbi.uliege.be/bitstream/2268/181954/1/userspaceio.pdf) (DPDK-based, if 100Gbps are enough. I know the authors if you need/want testing) and if you need something stateful e.g. TCP, [Warp17](http://warp17.net/) there is some evidence online that it keeps "tens of thousands" of TCP flows (beyond the kernel's capacity).

There is a "parallel" world to softeare-based traffic generators done in hardware. Some proprietary, but those open-source usually use a Tofino somewhere. I found this [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10048513) that gives an overview.

**Comment by mrbojangles3** [comment]
After a meeting, we decided the best path forward is to add code to the "normal" code path. Where there is already code working in multi-core fashion to process packets. The alternative path, not taken, would have had all the cores behaving like a dedicated RX core. This path probably makes assumptions about there only being a single rx core and we would be looking at adding code that does parallelism. The chose path seems like the least lift.
