### ISSUE TITLE
RFE - TestPMD Support for Multiple PCI Addresses

### ISSUE THREAD

**Issue by pradiptapks** [perftool-incubator/bench-trafficgen#81]
**Issue:** 
In the ShiftonStack NFV use case, the `dpdk-testpmd` pod cannot forward packets with `IO` forwarding mode using existing two PCI interface.

**Justification:** 
In ShiftonStack deployments, the `dpdk-testpmd` pod needs to be configured with `MAC` forwarding mode. To achieve a bidirectional throughput of 100Gbps from multiple trafficgen source, the application requires configuration with more than 2 PCI addresses along with the necessary **CPUs** and memory **hugepages**.

The test has been successfully verified through manual configuration in the `dpdk-testpmd` pod. However, automation through Crucible is necessary to collect metrics from K8s endpoints.

```bash
dpdk-testpmd  --lcores 0@10,1@11,2@12,3@13,4@14,5@15,6@16,7@17,8@18 --file-prefix server-1 --socket-mem 8192 --huge-dir /dev/hugepages  --allow 0000:05:00.0 --allow 0000:06:00.0 --allow 0000:07:00.0 --allow 0000:08:00.0 --allow 0000:09:00.0 --allow 0000:0a:00.0 --allow 0000:0b:00.0 --allow 0000:0c:00.0 -v -- --nb-ports 8 --nb-cores 8 --auto-start --stats-period=5 --rxq 1 --txq 1 --rxd 2048 --txd 2048 --max-pkt-len=9216 --rss-udp --burst=64 --mbuf-size=16384 --eth-peer 0,40:a6:b7:2a:89:ac --eth-peer 1,40:a6:b7:2a:89:ad --eth-peer 2,3c:fd:fe:ee:46:c0 --eth-peer 3,3c:fd:fe:ee:46:c1 --eth-peer 4,3c:fd:fe:ee:47:0c --eth-peer 5,3c:fd:fe:ee:47:0d --eth-peer 6,3c:fd:fe:ee:4c:50 --eth-peer 7,3c:fd:fe:ee:4c:51 --forward-mode mac

**Comment by atheurer** [comment]
@pradiptapks this feature has been completed with https://github.com/perftool-incubator/bench-trafficgen/pull/83
